spring.application.name=api

# Configurações do MySQL
spring.datasource.url=${DB_VOLLMED_URL}
spring.datasource.username=${DB_VOLLMED_USER}
spring.datasource.password=${DB_VOLLMED_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET}
